
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author guill
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_mensaje = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_ruta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jd_editFile = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txt_name1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_data = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_directory = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane1.setViewportView(ta_mensaje);

        jLabel2.setText("CLIENT MESSAGE");

        javax.swing.GroupLayout mensajeLayout = new javax.swing.GroupLayout(mensaje.getContentPane());
        mensaje.getContentPane().setLayout(mensajeLayout);
        mensajeLayout.setHorizontalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel2)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        mensajeLayout.setVerticalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Nombre del archivo:");

        txta_mensaje.setColumns(20);
        txta_mensaje.setRows(5);
        jScrollPane2.setViewportView(txta_mensaje);

        jButton8.setText("Crear Archivo");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel4.setText("Ruta:");

        jLabel5.setText("Crear Archivo");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name)
                            .addComponent(txt_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel5)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jLabel7.setText("Nombre del archivo:");

        ta_data.setColumns(20);
        ta_data.setRows(5);
        jScrollPane4.setViewportView(ta_data);

        jButton9.setText("Editar Archivo");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel8.setText("Edit File");

        javax.swing.GroupLayout jd_editFileLayout = new javax.swing.GroupLayout(jd_editFile.getContentPane());
        jd_editFile.getContentPane().setLayout(jd_editFileLayout);
        jd_editFileLayout.setHorizontalGroup(
            jd_editFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_editFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_editFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_editFileLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addGroup(jd_editFileLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_editFileLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_editFileLayout.setVerticalGroup(
            jd_editFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_editFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jd_editFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("CONNECT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("CLIENT");

        jButton2.setText("Create Dir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_directory.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_directory);

        jButton3.setText("Remove Dir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Move");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Create File");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Edit File");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Shutdown");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Connect
     *
     * @param evt Conecta al servidor en el puerto preestablecido
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            ta_mensaje.setVisible(true);
            myreg = LocateRegistry.getRegistry("192.168.0.14", port);
            
            inter = (FSInterface) myreg.lookup("remoteObject");
            ta_mensaje.setText("Servicio Listo =)");
            
            mensaje.setModal(true);
            mensaje.pack();
            mensaje.setVisible(true);
            mensaje.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            this.idClient = inter.addClient();
            inter.addBinnacle("[Client " + this.idClient + "] Client connected.");
            jLabel1.setText("CLIENT " + this.idClient);
            jd_editFile.setVisible(false);
            //fillTree(root, files[0].getParentFile());
            load();
            
        } catch (Exception e) {
            ta_mensaje.setText("Something went wrong");
            jd_editFile.setVisible(false);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            String nombre = JOptionPane.showInputDialog(this, "Ingrese nombre del directorio: ");
            if (nombre.replaceAll(" ", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacío.");
                throw new Exception("Vacio");
            }
            String ruta = JOptionPane.showInputDialog(this, "Ingrese ruta (Vacio es C:): ");
            boolean bool = inter.createDirectory("./C/" + ruta + "/" + nombre);
            if (bool) {
                inter.addBinnacle("[Client " + this.idClient + "] The directory \"C:/" + ruta + "" + nombre + "\" has been created.");
            }
            System.out.println("directory created :" + bool);
            load();
            if (!bool) {
                JOptionPane.showMessageDialog(this, "El Directorio ya Existe! ");
            }
        } catch (Exception e) {
        }
        

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            String ruta = JOptionPane.showInputDialog(this, "Ingrese ruta  a eliminar: ");
            boolean bool = inter.removeDirectoryOrFile("./C/" + ruta);
            System.out.println("directory deleted :" + bool);
            if (bool) {
                inter.addBinnacle("[Client " + this.idClient + "] The directory \"C:/" + ruta + "\" has been deleted.");
            }
            load();
            if (!bool) {
                JOptionPane.showMessageDialog(this, "El Directorio No Existe! ");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        try {
            // TODO add your handling code here:
            String nombre = JOptionPane.showInputDialog(this, "Archivo Deseado: ");
            if (nombre.replaceAll(" ", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacío.");
                throw new Exception("Vacio");
            }
            String target = JOptionPane.showInputDialog(this, "Ubicacion de Archivo: ");
            String location = JOptionPane.showInputDialog(this, "Nueva Ubicacion: ");
            if (!nombre.contains(".txt")) {
                boolean borrado = inter.removeDirectoryOrFile("./C/" + target + "/" + nombre);
                boolean movido = false;
                if (borrado) {
                    movido = inter.createDirectory("./C/" + location + "/" + nombre);
                }
                System.out.println("Borrado: " + borrado);
                System.out.println("Movido: " + movido);
                if (movido && borrado) {
                    inter.addBinnacle("[Client " + this.idClient + "] The file \"" + nombre + "\" has been moved from \"C:/" + target + "\" to \"C:/" + location + "\".");
                }
            } else {
                byte[] copy = inter.downloadFileFromServer("./C/" + target + "/" + nombre);
                boolean borrado = inter.removeDirectoryOrFile("./C/" + target + "/" + nombre);
                inter.uploadFileToServer(copy, "./C/" + location + "/" + nombre, copy.length);
                if (borrado) {
                    inter.addBinnacle("[Client " + this.idClient + "] The file \"" + nombre + "\" has been moved from \"C:/" + target + "\" to \"C:/" + location + "\".");
                }
            }
            load();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:

        jDialog1.setModal(true);
        jDialog1.pack();
        jDialog1.setVisible(true);
        jDialog1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        try {
            // TODO add your handling code here:
            String nombre = txt_name.getText().replaceAll(".txt", "");
            if (nombre.replaceAll(" ", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacío.");
                throw new Exception("Vacio");
            }
            String ruta = txt_ruta.getText();
            String mensaje = "0\r\n" + txta_mensaje.getText();
            byte[] b = mensaje.getBytes();
            inter.uploadFileToServer(b, "./C/" + ruta + "/" + nombre + ".txt", b.length);
            JOptionPane.showMessageDialog(this, "Archivo Creado");
            inter.addBinnacle("[Client " + this.idClient + "] The file \"" + nombre + ".txt\" has been created at \"C:/" + ruta + "\".");
            txt_name.setText("");
            txt_ruta.setText("");
            txta_mensaje.setText("");
            jDialog1.dispose();
            load();
        } catch (RemoteException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try {
            // TODO add your handling code here:
            target = JOptionPane.showInputDialog(this, "Archivo Deseado: ");
            if (target.replaceAll(" ", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacío.");
                throw new Exception("Vacio");
            }
            location = JOptionPane.showInputDialog(this, "Ubicacion de Archivo: ");
            datos = inter.downloadFileFromServer("./C/" + location + "/" + target);
            //servidor ->cliente:cache
            File file = new File("./cache/" + target);
            FileOutputStream fos = new FileOutputStream(file);
            fos.write(datos);
            fos.close();

            //cache:file -> Editor
            File cachedFile = new File("./cache/" + target);
            BufferedReader br = new BufferedReader(new FileReader(cachedFile));
            String validate = br.readLine();
            System.out.println("VALIDATING: " + validate);
            //Validation
            if (!validate.equals("0")) {
                JOptionPane.showMessageDialog(this, "ARCHIVO BLOQUEADO");
            } else {
                //Cambiar Bit validacion
                String contents = new String(Files.readAllBytes(Paths.get("./cache/" + target)));
                String newF = "1";
                for (int i = 1; i < contents.length(); i++) {
                    newF = newF + contents.charAt(i);
                }
                System.out.println("File contents: " + newF);
                inter.uploadFileToServer(newF.getBytes(), "./C/" + location + "/" + target, newF.length());
                //inter.addBinnacle("[Client " + this.idClient + "] The file \"" + target + "\" has been modified");

                txt_name1.setText(target);
                ta_data.setText(new String(datos).replaceFirst("0\r\n", ""));
                
                jd_editFile.setModal(true);
                jd_editFile.pack();
                jd_editFile.setVisible(true);
                jd_editFile.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
            
        } catch (Exception e) {
            //System.out.println(e);
        }

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        try {
            // TODO add your handling code here:
            String nombre = txt_name1.getText();
            if (nombre.replaceAll(" ", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo vacío.");
                throw new Exception("Vacio");
            }
            String mensaje = "0\r\n" + ta_data.getText();
            byte[] b = mensaje.getBytes();
            inter.uploadFileToServer(b, "./C/" + location + "/" + nombre, b.length);
            JOptionPane.showMessageDialog(this, "Archivo Editado");
            inter.addBinnacle("[Client " + this.idClient + "] The file \"" + target + "\" has been modified");
            
            txt_name.setText("");
            txt_ruta.setText("");
            txta_mensaje.setText("");
        } catch (RemoteException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hasta Luego!");
        try {
            inter.addBinnacle("[Client " + this.idClient + "] Client disconnected.");
        } catch (Exception ex) {
        }
        System.exit(0);

    }//GEN-LAST:event_jButton7MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            inter.addBinnacle("[Client " + this.idClient + "] Client disconnected.");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            inter.addBinnacle("[Client " + this.idClient + "] Client disconnected.");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    
    public void load() {
        try {
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("server:", true);
            File[] files = inter.listFiles("./C");
            fillTree1(root, files);
            tree = new JTree(root);
            jt_directory.setModel(tree.getModel());
        } catch (RemoteException ex) {
        }
        
    }
    
    public void fillTree1(DefaultMutableTreeNode dir, File[] files) {
        DefaultMutableTreeNode child;
        for (int i = 0; i < files.length; i++) {
            if (files[i].getPath().contains(".txt")) {
                child = new DefaultMutableTreeNode(files[i].getName());
                dir.add(child);
            } else {
                try {
                    child = new DefaultMutableTreeNode(files[i].getName());
                    dir.add(child);
                    fillTree1(child, inter.listFiles(files[i].getPath()));
                } catch (RemoteException ex) {
                }
            }
            
        }
    }
    
    public void fillTree(DefaultMutableTreeNode dir, File f) {
        if (!f.isDirectory()) {
            DefaultMutableTreeNode child = new DefaultMutableTreeNode(f.getName());
            dir.add(child);
        } else {
            DefaultMutableTreeNode child = new DefaultMutableTreeNode(f.getName());
            dir.add(child);
            File fList[] = f.listFiles();
            for (int i = 0; i < fList.length; i++) {
                fillTree(child, fList[i]);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_editFile;
    private javax.swing.JTree jt_directory;
    private javax.swing.JDialog mensaje;
    private javax.swing.JTextArea ta_data;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_name1;
    private javax.swing.JTextField txt_ruta;
    private javax.swing.JTextArea txta_mensaje;
    // End of variables declaration//GEN-END:variables
    File cachedFile;
    static int port = 6000;
    static Registry myreg;
    static FSInterface inter;
    static String target = "", location = "";
    JTree tree;
    byte datos[];
    int idClient = 0;
}
